### PR TITLE
tags and text initial escaping

### PR DESCRIPTION
**Pull request by semyont**
fixed initial escaping as you can see works for tags and urls
image
could you please generate minified version with this new code?
boynet great project idea i'm going to contribute as much as i can.

### CODE REVIEW

**Comment by boynet** [comment]
Thanks nice to see some interest on this.

you are missing closing `}` on the if statement.

**Comment by boynet** [comment]
we need to create some simple tests before I can merge this to make sure its doesn't break something else

**Comment by semyont** [comment]
Sounds good practice, also an automated min version on build success. 
Are you familiar with such framework or practice in JavaScript ?

**Comment by boynet** [comment]
I am familiar with gulp good enough?

**Pull request closed without merging**
